// Code generated by "stringer -type=Region"; DO NOT EDIT.

package icaoregion

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[AFI-1]
	_ = x[ASIA-2]
	_ = x[CAR-3]
	_ = x[EUR-4]
	_ = x[MID-5]
	_ = x[NAM-6]
	_ = x[NAT-7]
	_ = x[SAM-8]
}

const _Region_name = "UnknownAFIASIACAREURMIDNAMNATSAM"

var _Region_index = [...]uint8{0, 7, 10, 14, 17, 20, 23, 26, 29, 32}

func (i Region) String() string {
	if i >= Region(len(_Region_index)-1) {
		return "Region(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Region_name[_Region_index[i]:_Region_index[i+1]]
}
