name: borderforce_testing

services:
  borderforce:
    build:
      context: ../../
      dockerfile: docker/borderforce/Dockerfile
      target: dev
    restart: always
    depends_on:
      nats:
        condition: service_started
      pw_atc_api:
        condition: service_healthy
    environment:
      - CERT_FILE=/test/server.crt
      - KEY_FILE=/test/server.key
      - DEBUG=true
      - SINK=nats://nats:4222
    volumes:
      - type: bind
        source: ${TESTDIR}
        target: /test

  nats:
    image: nats:alpine
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    volumes:
      - type: bind
        source: ${TESTDIR}
        target: /test

  nats-client:
    build:
      context: ./nats-client
    depends_on:
      nats:
        condition: service_started

  pw_atc_api:
    build:
      context: ../../
      dockerfile: docker/pw_atc_api/Dockerfile
      target: dev
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=test
      - DATABASE_PASSWORD=test
      - DATABASE_NAME=atc_test
      - NATS=nats://nats:4222
    depends_on:
      nats:
        condition: service_started
      db:
        condition: service_healthy
    restart: always

  db:
    build:
      context: ./testdb/
    restart: always
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test

#  stunnel:
#    build:
#      context: ./stunnel
#    restart: always
#    depends_on:
#      borderforce:
#        condition: service_healthy
#
#  readsb:
#    build:
#      context: ./readsb
#    depends_on:
#      stunnel:
#        condition: service_healthy
