// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: lib/stickyfeeder/claims.proto

package stickyfeeder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AircraftClaim represents a claim broadcast from one instance
type AircraftClaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Icao          uint32                 `protobuf:"varint,2,opt,name=icao,proto3" json:"icao,omitempty"`
	FeederTag     string                 `protobuf:"bytes,3,opt,name=feeder_tag,json=feederTag,proto3" json:"feeder_tag,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sequence      uint64                 `protobuf:"varint,6,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AircraftClaim) Reset() {
	*x = AircraftClaim{}
	mi := &file_lib_stickyfeeder_claims_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AircraftClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AircraftClaim) ProtoMessage() {}

func (x *AircraftClaim) ProtoReflect() protoreflect.Message {
	mi := &file_lib_stickyfeeder_claims_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AircraftClaim.ProtoReflect.Descriptor instead.
func (*AircraftClaim) Descriptor() ([]byte, []int) {
	return file_lib_stickyfeeder_claims_proto_rawDescGZIP(), []int{0}
}

func (x *AircraftClaim) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *AircraftClaim) GetIcao() uint32 {
	if x != nil {
		return x.Icao
	}
	return 0
}

func (x *AircraftClaim) GetFeederTag() string {
	if x != nil {
		return x.FeederTag
	}
	return ""
}

func (x *AircraftClaim) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *AircraftClaim) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AircraftClaim) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// ClaimBatch allows efficient batching of multiple claims in one message
type ClaimBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Claims        []*AircraftClaim       `protobuf:"bytes,2,rep,name=claims,proto3" json:"claims,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimBatch) Reset() {
	*x = ClaimBatch{}
	mi := &file_lib_stickyfeeder_claims_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimBatch) ProtoMessage() {}

func (x *ClaimBatch) ProtoReflect() protoreflect.Message {
	mi := &file_lib_stickyfeeder_claims_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimBatch.ProtoReflect.Descriptor instead.
func (*ClaimBatch) Descriptor() ([]byte, []int) {
	return file_lib_stickyfeeder_claims_proto_rawDescGZIP(), []int{1}
}

func (x *ClaimBatch) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ClaimBatch) GetClaims() []*AircraftClaim {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *ClaimBatch) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_lib_stickyfeeder_claims_proto protoreflect.FileDescriptor

const file_lib_stickyfeeder_claims_proto_rawDesc = "" +
	"\n" +
	"\x1dlib/stickyfeeder/claims.proto\x12\fstickyfeeder\"\xb3\x01\n" +
	"\rAircraftClaim\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x12\n" +
	"\x04icao\x18\x02 \x01(\rR\x04icao\x12\x1d\n" +
	"\n" +
	"feeder_tag\x18\x03 \x01(\tR\tfeederTag\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bsequence\x18\x06 \x01(\x04R\bsequence\"\x80\x01\n" +
	"\n" +
	"ClaimBatch\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x123\n" +
	"\x06claims\x18\x02 \x03(\v2\x1b.stickyfeeder.AircraftClaimR\x06claims\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestampB\x1eZ\x1cplane.watch/lib/stickyfeederb\x06proto3"

var (
	file_lib_stickyfeeder_claims_proto_rawDescOnce sync.Once
	file_lib_stickyfeeder_claims_proto_rawDescData []byte
)

func file_lib_stickyfeeder_claims_proto_rawDescGZIP() []byte {
	file_lib_stickyfeeder_claims_proto_rawDescOnce.Do(func() {
		file_lib_stickyfeeder_claims_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lib_stickyfeeder_claims_proto_rawDesc), len(file_lib_stickyfeeder_claims_proto_rawDesc)))
	})
	return file_lib_stickyfeeder_claims_proto_rawDescData
}

var file_lib_stickyfeeder_claims_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lib_stickyfeeder_claims_proto_goTypes = []any{
	(*AircraftClaim)(nil), // 0: stickyfeeder.AircraftClaim
	(*ClaimBatch)(nil),    // 1: stickyfeeder.ClaimBatch
}
var file_lib_stickyfeeder_claims_proto_depIdxs = []int32{
	0, // 0: stickyfeeder.ClaimBatch.claims:type_name -> stickyfeeder.AircraftClaim
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lib_stickyfeeder_claims_proto_init() }
func file_lib_stickyfeeder_claims_proto_init() {
	if File_lib_stickyfeeder_claims_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lib_stickyfeeder_claims_proto_rawDesc), len(file_lib_stickyfeeder_claims_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lib_stickyfeeder_claims_proto_goTypes,
		DependencyIndexes: file_lib_stickyfeeder_claims_proto_depIdxs,
		MessageInfos:      file_lib_stickyfeeder_claims_proto_msgTypes,
	}.Build()
	File_lib_stickyfeeder_claims_proto = out.File
	file_lib_stickyfeeder_claims_proto_goTypes = nil
	file_lib_stickyfeeder_claims_proto_depIdxs = nil
}
