#!/command/with-contenv bash
#shellcheck shell=bash

set -eo pipefail

rm -rf /run/mlat-server > /dev/null 2>&1 || true
mkdir -p /run/mlat-server/workdir

fdmove -c 2 1 \
    $VENV/bin/python3 /opt/mlat-server/mlat-server \
        --client-listen 0.0.0.0:12346 \
        --basestation-listen 0.0.0.0:30003 \
        --motd "plane.watch:${HOSTNAME}" \
        --work-dir /run/mlat-server/workdir \
        --status-interval 3600 |
    sed --unbuffered '/^$/d' | 
    awk '{print "[mlat-server] " $0}'

sleep 5
