---
name: Test Container Builds

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:

  hadolint:
    name: Hadolint (Dockerfiles)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.3.0
        name: pw_atc_api
        with:
          dockerfile: docker/pw_atc_api/Dockerfile
          ignore: DL3007 DL3059
          format: tty
      - uses: hadolint/hadolint-action@v3.3.0
        name: pw_ingest
        with:
          dockerfile: docker/pw_ingest/Dockerfile
          ignore: DL3007 DL3059
          format: tty
      - uses: hadolint/hadolint-action@v3.3.0
        name: pw_router
        with:
          dockerfile: docker/pw_router/Dockerfile
          ignore: DL3007 DL3059
          format: tty
      - uses: hadolint/hadolint-action@v3.3.0
        name: pw_ws_broker
        with:
          dockerfile: docker/pw_ws_broker/Dockerfile
          ignore: DL3007 DL3059
          format: tty
      - uses: hadolint/hadolint-action@v3.3.0
        name: runway
        with:
          dockerfile: docker/runway/Dockerfile
          ignore: DL3007 DL3059 DL3018
          format: tty

  gochecks:
    name: Go Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.3'
          check-latest: true
      - name: go vet
        run: go vet ./...
      - name: go test
        run: go test -skip="TestRepeater" ./...
      - name: go test (with race detection)
        run: go test -race -skip="TestRepeater" ./...

  test_build:
    name: Test Build
    runs-on: ubuntu-latest
    needs: [hadolint, gochecks]
    strategy:
      matrix:
        image:
          - runway
          - pw_atc_api
          - pw_ingest
          - pw_router
          - pw_ws_broker
          - mlat-server
        arch:
          - linux/amd64
          - linux/arm64

    steps:

      # Check out our code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Get metadata from repo
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}

      # Set up QEMU for multi-arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up buildx for multi platform builds
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      # Test Build
      - name: Test Build - ${{ matrix.image }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/${{ matrix.image }}/Dockerfile
          no-cache: true
          platforms: ${{ matrix.arch }}
          push: false
          tags: test_${{ matrix.image }}_${{ matrix.arch }}
          labels: ${{ steps.meta.outputs.labels }}
